-- Reservas de pedidos y cobro transaccional de señas.

alter table public.leads
  add column if not exists fulfillment_type text not null default 'stock',
  add column if not exists reserved_variant_id integer references public.product_variants(id),
  add column if not exists reserved_inventory_unit_id bigint references public.inventory_units(id),
  add column if not exists reservation_expires_at timestamptz;

alter table public.leads
  drop constraint if exists leads_fulfillment_type_check;

alter table public.leads
  add constraint leads_fulfillment_type_check
  check (fulfillment_type in ('stock', 'a_pedido'));

create table if not exists public.order_reservations (
  id bigint generated by default as identity primary key,
  lead_id integer not null references public.leads(id) on delete cascade,
  product_variant_id integer not null references public.product_variants(id),
  inventory_unit_id bigint references public.inventory_units(id),
  quantity integer not null default 1 check (quantity > 0),
  status text not null default 'active'
    check (status in ('active', 'released', 'expired', 'converted', 'cancelled')),
  reserved_at timestamptz not null default now(),
  expires_at timestamptz not null,
  released_at timestamptz,
  released_by uuid,
  release_reason text,
  created_by uuid default auth.uid()
);

create unique index if not exists order_reservations_one_active_per_lead
  on public.order_reservations(lead_id)
  where status = 'active';

alter table public.order_reservations
  add column if not exists inventory_unit_id bigint references public.inventory_units(id);

create index if not exists order_reservations_variant_active_idx
  on public.order_reservations(product_variant_id)
  where status = 'active';

create table if not exists public.order_deposits (
  id bigint generated by default as identity primary key,
  lead_id integer not null references public.leads(id),
  sale_id bigint references public.sales(id),
  customer_id integer references public.customers(id),
  amount numeric not null check (amount > 0),
  currency text not null check (currency in ('ARS', 'USD', 'USDT')),
  amount_ars numeric not null check (amount_ars > 0),
  fx_rate_used numeric,
  payment_method_id integer references public.payment_methods(id),
  account_id bigint references public.accounts(id),
  reference text,
  notes text,
  status text not null default 'received'
    check (status in ('received', 'applied', 'refunded', 'released')),
  received_at timestamptz not null default now(),
  applied_at timestamptz,
  created_by uuid default auth.uid()
);

alter table public.order_deposits
  add column if not exists sale_id bigint references public.sales(id);

create index if not exists order_deposits_lead_idx on public.order_deposits(lead_id);

alter table public.order_reservations enable row level security;
alter table public.order_deposits enable row level security;

drop policy if exists order_reservations_authenticated_select on public.order_reservations;
create policy order_reservations_authenticated_select
  on public.order_reservations for select to authenticated using (true);

drop policy if exists order_deposits_authenticated_select on public.order_deposits;
create policy order_deposits_authenticated_select
  on public.order_deposits for select to authenticated using (true);

create or replace function public.reserve_order_stock(
  p_lead_id integer,
  p_variant_id integer,
  p_inventory_unit_id bigint default null,
  p_quantity integer default 1,
  p_expires_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lead public.leads%rowtype;
  v_stock integer;
  v_reserved integer;
  v_expires_at timestamptz := coalesce(p_expires_at, now() + interval '24 hours');
  v_reservation_id bigint;
  v_tracking_mode text;
  v_unit public.inventory_units%rowtype;
begin
  if p_quantity <= 0 then
    raise exception 'La cantidad a reservar debe ser mayor a cero';
  end if;

  select * into v_lead from public.leads where id = p_lead_id for update;
  if not found then raise exception 'Pedido no encontrado'; end if;
  if v_lead.status not in ('pendiente', 'sin_exito') then
    raise exception 'El pedido no admite una reserva en su estado actual';
  end if;

  perform public.release_expired_order_reservations();

  select stock into v_stock
  from public.product_variants
  where id = p_variant_id and active = true
  for update;
  if not found then raise exception 'Variante no encontrada'; end if;

  select p.inventory_tracking_mode into v_tracking_mode
  from public.product_variants v
  join public.products p on p.id = v.product_id
  where v.id = p_variant_id;

  if v_tracking_mode = 'serial' then
    if p_inventory_unit_id is null then
      raise exception 'Debes seleccionar el IMEI o codigo unico a reservar';
    end if;
    select * into v_unit
    from public.inventory_units
    where id = p_inventory_unit_id and variant_id = p_variant_id
    for update;
    if not found or v_unit.status <> 'available' then
      raise exception 'La unidad serializada seleccionada ya no esta disponible';
    end if;
  elsif p_inventory_unit_id is not null then
    raise exception 'La variante no utiliza unidades serializadas';
  end if;

  select coalesce(sum(quantity), 0) into v_reserved
  from public.order_reservations
  where product_variant_id = p_variant_id and status = 'active';

  if v_stock - v_reserved < p_quantity then
    raise exception 'No hay stock disponible para reservar esta variante';
  end if;

  update public.order_reservations
  set status = 'cancelled', released_at = now(), released_by = auth.uid(), release_reason = 'Reemplazada'
  where lead_id = p_lead_id and status = 'active';

  insert into public.order_reservations (lead_id, product_variant_id, inventory_unit_id, quantity, expires_at)
  values (p_lead_id, p_variant_id, p_inventory_unit_id, p_quantity, v_expires_at)
  returning id into v_reservation_id;

  if p_inventory_unit_id is not null then
    update public.inventory_units
    set status = 'reserved', updated_by = auth.uid()
    where id = p_inventory_unit_id;
    insert into public.inventory_unit_events (
      inventory_unit_id, event_type, from_status, to_status,
      related_table, related_id, notes
    ) values (
      p_inventory_unit_id, 'order_reserved', 'available', 'reserved',
      'leads', p_lead_id, 'Unidad reservada para pedido'
    );
  end if;

  update public.leads
  set reserved_variant_id = p_variant_id,
      reserved_inventory_unit_id = p_inventory_unit_id,
      reservation_expires_at = v_expires_at,
      product_status = 'reservado',
      updated_at = now()
  where id = p_lead_id;

  return jsonb_build_object('id', v_reservation_id, 'expires_at', v_expires_at);
end;
$$;

create or replace function public.release_expired_order_reservations()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  with expired as (
    update public.order_reservations
    set status = 'expired', released_at = now(), release_reason = 'Vencimiento automático'
    where status = 'active' and expires_at <= now()
    returning lead_id
  )
  update public.leads l
  set reserved_variant_id = null,
      reserved_inventory_unit_id = null,
      reservation_expires_at = null,
      product_status = case when l.fulfillment_type = 'a_pedido' then 'a_pedido' else 'en espera' end,
      updated_at = now()
  where l.id in (select lead_id from expired)
    and not exists (
      select 1 from public.order_reservations r
      where r.lead_id = l.id and r.status = 'active'
    );

  update public.inventory_units u
  set status = 'available', updated_by = auth.uid()
  where u.status = 'reserved'
    and u.id in (
      select inventory_unit_id
      from public.order_reservations
      where status = 'expired' and inventory_unit_id is not null
    );

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.collect_order_deposit(
  p_lead_id integer,
  p_register_id bigint,
  p_payment_method_id integer,
  p_amount numeric,
  p_currency text,
  p_amount_ars numeric,
  p_fx_rate numeric default null,
  p_reference text default null,
  p_account_id bigint default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lead public.leads%rowtype;
  v_register public.cash_registers%rowtype;
  v_deposit_id bigint;
  v_account_id bigint := p_account_id;
  v_method_name text;
  v_multiplier numeric := 1;
  v_net_amount_ars numeric := p_amount_ars;
  v_delay integer := 0;
  v_available_on date;
  v_accreditation_status text;
begin
  select * into v_register
  from public.cash_registers
  where id = p_register_id and user_id = auth.uid() and status = 'open'
  for update;
  if not found then raise exception 'Debes tener una caja abierta para cobrar la seña'; end if;

  select * into v_lead from public.leads where id = p_lead_id for update;
  if not found then raise exception 'Pedido no encontrado'; end if;
  if v_lead.status in ('cancelado', 'vendido') then raise exception 'El pedido no admite señas'; end if;

  select name, account_id, greatest(coalesce(multiplier, 1), 1), coalesce(accreditation_delay_business_days, 0)
    into v_method_name, v_account_id, v_multiplier, v_delay
  from public.payment_methods where id = p_payment_method_id;
  if not found then raise exception 'Método de pago no encontrado'; end if;
  if lower(v_method_name) = 'transferencia' then
    v_account_id := p_account_id;
  end if;
  if v_account_id is null then raise exception 'El método no tiene cuenta de acreditación'; end if;

  v_net_amount_ars := p_amount_ars / v_multiplier;
  v_available_on := public.add_business_days(current_date, v_delay);
  v_accreditation_status := case when v_available_on > current_date then 'pending' else 'credited' end;

  insert into public.order_deposits (
    lead_id, customer_id, amount, currency, amount_ars, fx_rate_used,
    payment_method_id, account_id, reference, notes
  ) values (
    p_lead_id, v_lead.customer_id, p_amount, p_currency, p_amount_ars, p_fx_rate,
    p_payment_method_id, v_account_id, p_reference, p_notes
  ) returning id into v_deposit_id;

  insert into public.account_movements (
    account_id, type, amount, currency, amount_ars, fx_rate_used,
    related_table, related_id, notes, movement_date,
    accreditation_status, available_on
  ) values (
    v_account_id, 'income',
    case when p_currency = 'ARS' then v_net_amount_ars else p_amount / v_multiplier end,
    p_currency, v_net_amount_ars, p_fx_rate,
    'order_deposits', v_deposit_id,
    'Seña pedido #' || p_lead_id || ' - ' || v_method_name,
    current_date, v_accreditation_status, v_available_on
  );

  insert into public.cash_register_movements (
    cash_register_id, type, amount, currency, notes, related_table, related_id,
    created_by, payment_method_id, payment_method_name, reference,
    multiplier, net_amount, accreditation_status, available_on, account_id
  ) values (
    p_register_id, 'income', p_amount, p_currency,
    'Seña pedido #' || p_lead_id || ' - ' || v_method_name,
    'order_deposits', v_deposit_id, auth.uid(), p_payment_method_id,
    v_method_name, p_reference, v_multiplier, p_amount / v_multiplier,
    v_accreditation_status, v_available_on, v_account_id
  );

  update public.leads
  set deposit_paid = true,
      deposit_amount = p_amount,
      deposit_currency = p_currency,
      updated_at = now()
  where id = p_lead_id;

  return jsonb_build_object('deposit_id', v_deposit_id, 'amount_ars', p_amount_ars);
end;
$$;

create or replace function public.convert_order_reservation(
  p_lead_id integer,
  p_sale_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.order_reservations
  set status = 'converted', released_at = now(), release_reason = 'Convertida a venta'
  where lead_id = p_lead_id and status = 'active';

  update public.leads
  set reserved_variant_id = null,
      reserved_inventory_unit_id = null,
      reservation_expires_at = null,
      updated_at = now()
  where id = p_lead_id;
end;
$$;

create or replace function public.apply_order_deposits_to_sale(
  p_lead_id integer,
  p_sale_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.order_deposits
  set status = 'applied', applied_at = now(), sale_id = p_sale_id
  where lead_id = p_lead_id and status = 'received';
end;
$$;

create or replace function public.release_order_reservation(
  p_lead_id integer,
  p_reason text default 'Cancelación del pedido'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.order_reservations
  set status = 'released', released_at = now(), released_by = auth.uid(), release_reason = p_reason
  where lead_id = p_lead_id and status = 'active';

  update public.inventory_units u
  set status = 'available', updated_by = auth.uid()
  where u.status = 'reserved'
    and u.id in (
      select inventory_unit_id
      from public.order_reservations
      where lead_id = p_lead_id and status = 'released' and inventory_unit_id is not null
    );

  update public.leads
  set reserved_variant_id = null,
      reserved_inventory_unit_id = null,
      reservation_expires_at = null,
      product_status = case when fulfillment_type = 'a_pedido' then 'a_pedido' else 'en espera' end,
      updated_at = now()
  where id = p_lead_id;
end;
$$;
